# Generated by Django 4.0.4 on 2022-04-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True)),
                ('ore_lavorative', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Totale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True)),
                ('total_ore', models.FloatField()),
            ],
        ),
    ]
